language: php
git:
  dept: 1
php:
  - 5.6
  - 7.0
  - 7.1
matrix:
  fast_finish: true
sudo: false
install:
  - travis_retry composer install --no-interaction
  - wget -c -nc --retry-connrefused --tries=0 https://github.com/php-coveralls/php-coveralls/releases/download/v2.0.0/php-coveralls.phar
  - chmod +x php-coveralls.phar
  - php php-coveralls.phar --version
before_script:
  - mkdir -p build/logs
  - ls -al
script: vendor/bin/phpunit --configuration phpunit.xml --coverage-clover build/logs/clover.xml
after_success:
  - travis_retry php php-coveralls.phar -v
  - bash <(curl -s https://codecov.io/bash)
branches:
  only: master
notifications:
  email:
    on_success: never
    on_failure: always
cache:
  directories:
    - vendor
    - $HOME/.cache/composer